wastewatch/urls.py
from django.contrib import admin
from .views import main_page, logout, view_report, AdminUserView
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin_url'),
    path('accounts/', include('allauth.urls')),
    path('accounts/logout', logout, name='logout'),
    path('', main_page, name='main_page'),
    path('report/', views.submit_report, name='upload_file'),
    path('report/success/', views.report_success, name='upload_success'),
    path('view-reports/<int:question_id>', views.view_report, name='view_report'),
    path('report_resolved_success/', views.report_resolved_success, name='report_resolved_success'),
    path('my_reports/', views.my_reports, name='my_reports'),
    path('view_my_report/<int:report_id>', views.view_my_report, name='view_my_report'),
    path('view_admin_page/', AdminUserView.as_view(), name='admin_page')
]

wastewatch/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from storages.backends.s3boto3 import S3Boto3Storage
from django.contrib.auth.models import User



class Report(models.Model):
    id = models.AutoField(primary_key=True, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.TextField(max_length=100)
    description = models.TextField(max_length=500)
    text_file = models.FileField()
    image_file = models.ImageField()
    date = models.DateTimeField(help_text="Select the time of the report")
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    REPORT_STATUS = (
        (0, 'New'),
        (1, 'In Progress'),
        (2, 'Resolved'),
    )
    status = models.PositiveSmallIntegerField(choices=REPORT_STATUS, default=0)
    resolve_explanation = models.TextField(null=True, max_length=500)


class ReportStorage(S3Boto3Storage):
    location = 'reports'
    default_acl = 'public-read'
    file_overwrite = False

wastewatch/forms.py
from django import forms
from django.forms import ModelForm
from .models import Report


class SubmitReportForm(ModelForm):
    latitude = forms.FloatField(required=False, widget=forms.HiddenInput())
    longitude = forms.FloatField(required=False, widget=forms.HiddenInput())
    file = forms.FileField(label='Upload File', required=False,
                           widget=forms.FileInput(attrs={'accept': '.pdf, .txt, .jpg, .png', 'class': 'form-control-file'}))
    date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control-file'}))

    class Meta:
        model = Report
        fields = ['title', 'description', 'file', 'latitude', 'longitude']
        exclude = ['user', 'text_file', 'image_file', 'date', 'status', 'resolve_explanation']
    widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Title', 'max_length': 100}),
        'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 1, 'placeholder': 'Enter Description'}),
        'file': forms.FileField(widget=forms.FileInput(attrs={'style': 'display: 0;', 'accept': '.txt,.pdf,.jpg'})),
    }


class AdminReportForm(ModelForm):
    REPORT_STATUS_CHOICES = (
        (1, "In Progress"),
        (2, "Resolved"),
    )
    status = forms.ChoiceField(choices=REPORT_STATUS_CHOICES)

    class Meta:
        model = Report
        fields = ['status', 'resolve_explanation']
        exclude = ['user', 'title', 'description', 'file', 'date', 'text_file', 'image_file']
    widgets = {
        'resolve_explanation': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        'status': forms.RadioSelect(attrs={'class': 'form-select visually-hidden'})
    }

wastewatch/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import logout as auth_logout
from django.shortcuts import render, redirect, get_object_or_404
from . import settings
from django.http import HttpResponseForbidden
from .forms import SubmitReportForm, AdminReportForm
from .models import Report
import mimetypes
import operator
import boto3  #needed by test.py for some reason

def main_page(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return AdminUserView.as_view()(request)
        else:
            return RegularUserView.as_view()(request)
    else:
        return AnonymousUserView.as_view()(request)

class RegularUserView(LoginRequiredMixin, TemplateView):
    template_name = 'common.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        context['reports'] = Report.objects.filter(user=self.request.user)
        context['count'] = (Report.objects.filter(user=self.request.user).count()
                            - Report.objects.filter(user=self.request.user, status=2).count())
        return context

class AdminUserView(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    template_name = 'admin.html'

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        context['reports'] = sorted(Report.objects.all(), reverse=True, key=operator.attrgetter('date'))
        context['new'] = Report.objects.filter(status=0).count()
        context['progress'] = Report.objects.filter(status=1).count()
        return context

class AnonymousUserView(TemplateView):
    template_name = 'anonymous.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def logout(request):
    auth_logout(request)
    return main_page(request)


def submit_report(request):
    google_maps_api_key = settings.GOOGLE_MAPS_API_KEY
    google_maps_map_id = settings.GOOGLE_MAPS_MAP_ID
    if request.method == 'POST':
        form = SubmitReportForm(request.POST, request.FILES)
        if form.is_valid():
            report = form.save(commit=False)
            date = form.cleaned_data['date']
            latitude = form.cleaned_data['latitude']
            longitude = form.cleaned_data['longitude']
            report.date = date
            report.latitude = latitude
            report.longitude = longitude
            '''
            if a file was uploaded, use mimetypes to determine the file type
            '''
            if 'file' in request.FILES:

                uploaded_file = form.cleaned_data['file']
                mime_type = mimetypes.guess_type(uploaded_file.name)[0]
                if mime_type in ['text/plain', 'application/pdf']:
                    report.text_file = uploaded_file
                elif mime_type in ['image/jpeg', 'image/png']:
                    report.image_file = uploaded_file
            if request.user.is_authenticated:
                report.user = request.user
            report.save()
            return redirect('upload_success')
    else:
        form = SubmitReportForm()

    context = {'form': form,
               'google_maps_api_key': google_maps_api_key,
               'google_maps_map_id': google_maps_map_id}
    return render(request, 'report.html', context)

def report_success(request):
    return render(request, 'report_success.html')

def view_report(request, question_id):
    report = get_object_or_404(Report, pk=question_id)
    if not request.user.is_staff:
        return HttpResponseForbidden("Sorry, you don't have permission to view this report")
    if request.method == 'POST':
        form = AdminReportForm(request.POST, instance=report)
        if form.is_valid():
            form.save()
            return redirect('report_resolved_success')
    form = AdminReportForm(instance=report)
    if report.status == 0:
        report.status = 1
        report.save()

    google_maps_api_key = settings.GOOGLE_MAPS_API_KEY
    google_maps_map_id = settings.GOOGLE_MAPS_MAP_ID
    context = {'form': form, 'report': report, 'google_maps_api_key': google_maps_api_key,
               'google_maps_map_id': google_maps_map_id}
    return render(request, 'view_report.html', context)


def report_resolved_success(request):
    return render(request, 'report_resolved_success.html')


def my_reports(request):
    user_reports = Report.objects.filter(user=request.user)
    new = user_reports.filter(status=0).count()
    progress = user_reports.filter(status=1).count()
    total = user_reports.count()

    return render(request, 'my_reports.html', {
        'user_reports': sorted(user_reports, reverse=True, key=operator.attrgetter('date')),
        'new': new,
        'progress': progress,
        'total': total,
    })


def view_my_report(request, report_id):
    report = get_object_or_404(Report, pk=report_id)
    google_maps_api_key = settings.GOOGLE_MAPS_API_KEY
    google_maps_map_id = settings.GOOGLE_MAPS_MAP_ID
    context = {'report': report, 'google_maps_api_key': google_maps_api_key,
               'google_maps_map_id': google_maps_map_id}
    return render(request, 'view_my_report.html', context)

wastewatch/templates/admin.html
{% extends 'base.html' %}
{% load report_tags %}
{% block content %}
    <h1 class="mx-3">Hello {{ request.user }}!</h1>
    <p class="mx-3">
        {% if new == 1 %}
            There is 1 new report
        {% else %}
            There are {{ new }} new reports
        {% endif %}
        and
        {% if progress == 1 %}
            1 report in progress.
        {% else %}
            {{ progress }} reports in progress.
        {% endif %}
    </p>
    <p class="mx-3">Select a report to review</p>
    <div class="container mb-3 d-flex justify-content-end">
        <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false" id="custom-dropdown-btn">
                Sort Reports
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#" id="sort-lr" onclick="sortByDate('asc')">Least Recent</a></li>
                <li><a class="dropdown-item active" href="#" id="sort-mr" onclick="sortByDate('desc')">Most Recent</a></li>
                <li><a class="dropdown-item" href="#" id="sort-nf" onclick="sortByStatus('asc')">Status (New First)</a></li>
                <li><a class="dropdown-item" href="#" id="sort-rf" onclick="sortByStatus('desc')">Status (Resolved First)</a></li>
            </ul>
        </div>
    </div>
    <div class="container" id="report-cards-container">
        <div class="row row-cols-lg-2 g-3" id="report-cards">
            {% for report in reports %}
                <div class="col report-card" data-date="{{ report.date }}" data-status="{{ report.status }}">
                    <a href="{% url 'view_report' report.pk %}" style="text-decoration: none;">
                        <div class="card h-100" id="reports-array-card">
                            <div class="card-body">
                                <h5 class="card-title">{{ report.title|truncatechars:40 }}</h5>
                                {% if not report.user %}
                                    <p class="card-text">User: Anonymous</p>
                                {% else %}
                                    <p class="card-text">User: {{ report.user }}</p>
                                {% endif %}
                                <p class="card-text">Report Date: {{ report.date }}</p>
                                <p class="card-text">
                                    {% if report.status == 0 %}
                                    <i class="bi bi-save"></i> <span class="fs-6"> New</span>
                                    {% elif report.status == 1 %}
                                    <i class="bi bi-arrow-repeat"></i> <span class="fs-6"> In Progress</span>
                                    {% else %}
                                    <i class="bi bi-check-circle"></i> <span class="fs-6"> Resolved</span>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <script>
        function convertTime(dateData) {
            let time = "00:00";
            if (dateData.length > 2) {
                                let timeData = dateData[2].split(" ");
                const pm = timeData[2]==="p.m."
                let hm = timeData[1].split(":");
                let hour = parseInt(hm.at(0));
                let minute;
                if (hm.length > 1) {
                    minute = parseInt(timeData[1].split(":").at(1));
                }
                else {
                    minute = 0;
                }
                if (pm && hour < 12){
                    hour += 12;
                }
                time = hour.toString() + ":" + minute.toString();
            }

            let dateString = dateData[0] + "," + dateData[1] + " " + time;
            return new Date(dateString);
        }

        function sortByDate(order) {
            document.querySelectorAll('.dropdown-item').forEach(item => {
                item.classList.remove('active');
            });
            if (order === 'asc') {
                document.getElementById('sort-lr').classList.add('active');
            }
            else {
                document.getElementById('sort-mr').classList.add('active');
            }

            const cardsContainer = document.getElementById("report-cards");
            const cards = Array.from(cardsContainer.querySelectorAll(".report-card"));

            cards.sort((a, b) => {
                const dateA = convertTime(a.getAttribute("data-date").split(','));
                const dateB = convertTime(b.getAttribute("data-date").split(','));
                return order === 'asc' ? dateA - dateB : dateB - dateA;
            });

            cards.forEach(card => {
                cardsContainer.appendChild(card);
            });
        }

        function sortByStatus(order) {
            document.querySelectorAll('.dropdown-item').forEach(item => {
                item.classList.remove('active');
            });
            if (order === 'asc') {
                document.getElementById('sort-nf').classList.add('active');
            }
            else {
                document.getElementById('sort-rf').classList.add('active');
            }

            const cardsContainer = document.getElementById("report-cards");
            const cards = Array.from(cardsContainer.querySelectorAll(".report-card"));

            cards.sort((a, b) => {
                const statusA = parseInt(a.getAttribute("data-status"));
                const statusB = parseInt(b.getAttribute("data-status"));
                return order === 'asc' ? statusA - statusB : statusB - statusA;
            });

            cards.forEach(card => {
                cardsContainer.appendChild(card);
            });
        }
    </script>
{% endblock %}

wastewatch/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WasteWatch</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"
          integrity="sha384-4LISF5TTJX/fLmGSxO53rV4miRxdg84mZsxmO8Rx5jGtp/LbrixFETvWa5a6sESd" crossorigin="anonymous">
    <style>
        body {
            margin: 0;
            font-family: "Courier New", 'Roboto', sans-serif;
            color: #ffddb3;
            font-stretch: expanded;
            background: rgb(51,74,67);
            background: linear-gradient(90deg, rgba(51,74,67,1) 9%, rgba(77,143,124,1) 65%, rgb(116, 161, 148) 100%);
            overflow-x: hidden;
        }

        footer {
            background-color: #ffddb3;
            font-family: "Courier New", 'Roboto', sans-serif;
            border-top: 2px solid #333;
            color: #333;
        }

        .navbar {
            transition: top 0.5s ease-in-out;
            display: none;
            background-color: #ffddb3;
            opacity: 1;
            display: block;
            font-family: "Courier New", 'Roboto', sans-serif;
            border-bottom: 2px solid #333;
        }

        .content {
            padding: 100px 20px 200px 20px;
            font-family: "Courier New", 'Roboto', sans-serif;
            color: #ffddb3;
            text-align: left;
        }

        .navbar-nav {
            color: #cc7000;
        }


        #accounts-pages-link {
            font-weight: bold;
            color: #cc7000;
            opacity: 1;
        }

        #accounts-pages-link:hover {
            opacity: 0.5;
        }


        #custom-btn {
            border: 0.2rem solid #ffddb3;
            color: #ffddb3;
            font-family: "Courier New", 'Roboto', sans-serif;
            font-weight: bold;
            opacity: 1;
        }

        #custom-btn:hover {
            background-color: #ffddb3;
            color: #cc7000;
            opacity: 1;
        }

        #custom-dropdown-btn {
            border: 2px solid #ffddb3;
            background-color: #ffddb3;
            color: #333;
            opacity: 1;
        }


        #custom-report-card-title {
            width: 100%;
            overflow-x: scroll;
            background-color: #ffddb3;
            display: flex;
            flex-direction: column;
        }

        #custom-report-card-desc {
            width: 100%;
            overflow-x: scroll;
            background-color: #ffddb3;
            display: flex;
            flex-direction: column;
        }

        #custom-report-card-files-map {
            width: 100%;
            overflow-x: scroll;
            background-color: #ffddb3;
            display: flex;
            flex-direction: column;
        }

        #custom-report-card-img {
            height: auto;
            max-width: 100%;
        }

        #custom-submit-btn {
            background-color: #cc7000;
            color: #ffddb3;
            font-family: "Courier New", 'Roboto', sans-serif;
        }

        #custom-submit-btn:hover {
            background-color: #ffddb3;
            color: #cc7000;
        }

        #report-map {
            height: 400px;
            color: #333;
            border-radius: 5px;
        }

        #review-report-map {
            height: 400px;
            color: #333;
            border-radius: 3px;
        }

        #reports-array-card {
            background-color: #ffddb3;
            border: 2px #ffddb3 solid;
            transition: opacity 0.5s ease;
        }

        #reports-array-card:hover {
            opacity: 0.5;
        }

        #table-truncate {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        #text-wrap-custom {
            overflow-wrap: break-word;
            word-wrap: break-word;
            hyphens: auto;
        }

        @media (min-width: 768px) {
            #wastewatch-logo-container {
                font-size: 6rem;
            }
        }

        @keyframes typing {
            from { width: 0; }
            to { width: 100%; }
        }

        @keyframes blink {
            50% { opacity: 0; }
        }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand d-flex align-items-center" href="/">
              <i class="bi bi-eye me-2 mt-1"></i>
              <span class="text-bold">WasteWatch</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/report">Submit Report</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="/my_reports">My Reports</a>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav">
                    {% if request.user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/logout">Log Out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/login">Log In</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<!-- Page Content -->
<div class="container">
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</div>

<!-- Footer -->
<footer class="fixed-bottom py-2">
    <div class="container text-center">
        <p class="mb-0"><small>WasteWatch is a class project for CS 3240 at the University of Virginia.<em> No reports will be
            processed.</em> No real-world reports should be filed with WasteWatch.</small></p>
    </div>
</footer>

<!-- Bootstrap scripts -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>
</html>

wastewatch/templates/common.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mx-3">
        <h1>Welcome {{ request.user }}!</h1>
        <p>WasteWatch is a platform for reporting environmental offenses.<br>
            Please help us accomplish our mission to keep our environment clean and healthy.</p>
        <a href="{% url 'my_reports' %}" class="btn" id="custom-btn">View your reports</a>
        <a href="{% url 'upload_file' %}" class="btn" id="custom-btn">Submit new report</a>
    </div>
{% endblock %}

wastewatch/templates/report.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Submit Report</title>
        <style>
            #asterisk {
                color: #cc7000;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
    <h2 class="mx-3">File a Report to WasteWatch</h2>
    <p class="mx-3"><span id="asterisk">*</span><small> indicates a required field</small></p>
    <form class="mx-3" method="post" enctype="multipart/form-data" onsubmit="return validateForm()">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Report Title<span id="asterisk">*</span></label>
            {% render_field form.title placeholder="Enter a title for your report" class+="form-control" rows="1" id="report-title" %}
        </div>
        <div class="mb-3">
            <label class="form-label">Date and Time of the Offense<span id="asterisk">*</span></label>
            {% render_field form.date placeholder="Enter the date and time of the offense" class+="form-control" id="report-date" %}
        </div>
        <div class="mb-3">
            <label class="form-label">Describe the environmental offense you witnessed<span
                    id="asterisk">*</span></label>
            {% render_field form.description placeholder="Enter a description for your report..." class+="form-control" rows="5" id="report-desc" %}
        </div>
        <div class="mb-3">
            <label class="form-label">Use the map to place a pin at the location of the offense<span
                    id="asterisk">*</span></label>
            <div id="report-map"></div>
            <input type="hidden" id="id_latitude" name="latitude" value="">
            <input type="hidden" id="id_longitude" name="longitude" value="">
        </div>
        <div class="mb-3">
            <label class="form-label">Upload a supporting image, text file, or PDF</label><br>
            {% render_field form.file class+="form-control" type="file" id="form-file" %}
        </div>
        <button type="submit" class="btn" id="custom-submit-btn">Submit Report</button>
    </form>
    </body>
    <script>
        let map, infoWindow, marker;

        async function initMap() {
            const { Map, Marker } = await google.maps.importLibrary("maps");
            const cvilleLatlng = { lat: 38.035192, lng: -78.503805 };

            map = new google.maps.Map(document.getElementById("report-map"), {
                zoom: 15,
                center: cvilleLatlng,
                mapId: "{{ google_maps_map_id }}",
            });

            infoWindow = new google.maps.InfoWindow({
                content: "Click the map to report location",
                position: cvilleLatlng,
            });

            infoWindow.open(map);

            map.addListener("click", (mapsMouseEvent) => {
                infoWindow.close();
                const pos = {
                    lat: mapsMouseEvent.latLng.lat(),
                    lng: mapsMouseEvent.latLng.lng()
                };
                if (marker) {
                    marker.setPosition(pos);
                } else {
                    marker = new google.maps.Marker({
                        position: pos,
                        map: map,
                        title: "Report Location",
                        draggable: true,
                    });
                }
                document.getElementById("id_latitude").value = pos.lat;
                document.getElementById("id_longitude").value = pos.lng;

                marker.addListener("dragend", () => {
                    const newPos = marker.getPosition();
                    document.getElementById("id_latitude").value = newPos.lat();
                    document.getElementById("id_longitude").value = newPos.lng();
                });
            });
        }

        function validateForm() {
            const date = Date.parse(document.getElementById("report-date").value);
            if (date > Date.now())
            {
                alert("Please select a date in the past.");
                return false;
            }

            const latitude = document.getElementById("id_latitude").value;
            const longitude = document.getElementById("id_longitude").value;
            if (latitude === "" || longitude === "") {
                alert("Please select a location on the map to submit a report.");
                return false;
            }
            return true;
        }

        if (typeof window.initMap === "undefined") {
            window.initMap = initMap;
        } else {
            console.warn("initMap already defined.");
        }

        initMap();
    </script>

    <script async
        src="https://maps.googleapis.com/maps/api/js?key={{ google_maps_api_key }}&loading=async&callback=initMap">
    </script>
{% endblock %}

wastewatch/templates/report_resolved_success.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <meta http-equiv="refresh" content="8; url=/" />
    <div class="container text-center">
        <h1>Thank you for updating this report!</h1>
        <p>You will be automatically redirected to the reports page in a few seconds.</p>
        <a class="btn" href="/" id="custom-btn">Return Now</a>
    </div>
{% endblock %}

wastewatch/templates/report_success.html
{% extends 'base.html' %}
{% block content %}

<div class="container-sm text-left">
    <h1>Success!</h1>
    <p>Your report has been successfully submitted to WasteWatch!<br>
        A WasteWatch administrator will review your report promptly.<br>
        Thank you for helping to keep our environment clean!
    </p>
    {% if request.user.is_authenticated %}
        <p>
            You can view the status of your report(s) on the "My Reports" page, or by clicking
            <a href="/my_reports" style="color: #cc7000;">here</a>.
        </p>
    {% endif %}
</div>
{% endblock %}